blank_issues_enabled: true
contact_links:
  - name: Questions and Discussions
    url: https://github.com/Marohn-Group/mrfmsim/discussions
    about: Ask questions and discuss ideas with the community

